# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "Printing the pipeline id"
    parameters:
      pl_id:
        type: string
        default: << pipeline.id >>
    steps:
      - run: echo "This is pipeline ID -- << parameters.pl_id >>"
  fail_test:
    description: "command will cause a fail by returning 1"
    steps:
      - run: return 1
      - run:
          command: echo "Yes we did that."
          when: on_fail


defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/projects

jobs:
  pipline_info:
    <<: *defaults
    steps:
      - checkout
      - print_pipeline_id:
          pl_id: << pipeline.id >>
  will_fail:
    <<: *defaults
    steps:
      - checkout
      - fail_test

workflows:
  do_the_output_thing:
    jobs:
      - will_fail

