# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/projects
jobs:
  save_hello_world_output:
    <<: *defaults
    steps:
      - checkout
      - run: echo "!!!Hello to the world of CI/CD!!!" > output.txt
      - run: cat output.txt
      - persist_to_workspace:
          root: ~/projects
          paths:
            - .
  print_hello_file:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/projects
      - run: ls           
      - run: cat output.txt  

workflows:
  # Name the workflow "welcome"
  do_the_output_thing:
    jobs:
      - save_hello_world_output
      - print_hello_file:
          requires:
            - save_hello_world_output

