# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  saying_hello_to_the_world:
    description: "Say hello and seeing if jobs will run"
    parameters:
      to:
        type: string
        default: World
    steps:
      - run: echo "Hello << parameters.to >>"
      - run: pwd
      - run: echo "That is the current directory we are working with"
  print_pipeline_id:
    description: "Printing the pipeline id"
    parameters:
      pl_id:
        type: string
        default: << pipeline.id >>
    steps:
      - run: echo "This is pipeline ID: << parameters.pl_id >>"

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/projects

jobs:
  greetings_and_info:
    <<: *defaults
    steps:
      - checkout
      - saying_hello_to_the_world:
          to: Stephen
      - print_pipeline_id:
          pl_id: << pipeline.id >>

workflows:
  do_the_output_thing:
    jobs:
      - greetings_and_info

